Changes inline with ror data import
CottageLabs/jct pull request #85
Opened 2022-01-23 21:36 UTC by anusharanganathan

This is a PR for https://github.com/antleaf/jct-project/issues/372
The API has changed to ror dataset. Changes in front end to reflect that.

2022-01-25 14:33 UTC, richard-jones requested changes
Minor null checks required

2022-01-25 14:33 UTC, richard-jones commented on static/js/jct.js
> +            if ('country_name' in obj.country && obj.country.country_name) {
presumably still need the `obj.country` check, like:

```
if (obj.country && 'country_name' in obj.country && obj.country.country_name) {
```

2022-01-25 14:33 UTC, richard-jones commented on static/js/jct.js
> +            if ('country_name' in obj.country && obj.country.country_name) {
and same here

2022-02-01 14:38 UTC, richard-jones approved these changes
Looks good, we need to sync up on the release of this to do the back and front ends at the same time

2022-04-22 11:50 UTC, anusharanganathan commented
This is no longer relevant with new autocomplete index

2022-04-22 11:50 UTC, closed without merging